apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-exporter
  namespace: heatpump
spec:
  replicas: 1
  selector:
    matchLabels:
    app: fake-exporter
  template:
    metadata:
      labels:
        app: fake-exporter
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

